// Generated by gencpp from file learn_msg_filter/NewString.msg
// DO NOT EDIT!


#ifndef LEARN_MSG_FILTER_MESSAGE_NEWSTRING_H
#define LEARN_MSG_FILTER_MESSAGE_NEWSTRING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace learn_msg_filter
{
template <class ContainerAllocator>
struct NewString_
{
  typedef NewString_<ContainerAllocator> Type;

  NewString_()
    : header()
    , st()  {
    }
  NewString_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , st(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _st_type;
  _st_type st;





  typedef boost::shared_ptr< ::learn_msg_filter::NewString_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learn_msg_filter::NewString_<ContainerAllocator> const> ConstPtr;

}; // struct NewString_

typedef ::learn_msg_filter::NewString_<std::allocator<void> > NewString;

typedef boost::shared_ptr< ::learn_msg_filter::NewString > NewStringPtr;
typedef boost::shared_ptr< ::learn_msg_filter::NewString const> NewStringConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learn_msg_filter::NewString_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learn_msg_filter::NewString_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace learn_msg_filter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'learn_msg_filter': ['/home/ak/Git/test_ws/src/learn_msg_filter/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::learn_msg_filter::NewString_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learn_msg_filter::NewString_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_msg_filter::NewString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learn_msg_filter::NewString_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_msg_filter::NewString_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learn_msg_filter::NewString_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learn_msg_filter::NewString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2d740582137ac619a96dd7006cca5d3";
  }

  static const char* value(const ::learn_msg_filter::NewString_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2d740582137ac61ULL;
  static const uint64_t static_value2 = 0x9a96dd7006cca5d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::learn_msg_filter::NewString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learn_msg_filter/NewString";
  }

  static const char* value(const ::learn_msg_filter::NewString_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learn_msg_filter::NewString_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
string st\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::learn_msg_filter::NewString_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learn_msg_filter::NewString_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.st);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NewString_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learn_msg_filter::NewString_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learn_msg_filter::NewString_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "st: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.st);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARN_MSG_FILTER_MESSAGE_NEWSTRING_H
